//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.5456
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBOutput.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBOutput.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   select name from sys.databases に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rcDataBaseName {
            get {
                return ResourceManager.GetString("rcDataBaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT 
        ///    [creation_time]             AS [コンパイル時刻], 
        ///    [last_execution_time]       AS [前回の実行時刻], 
        ///    [execution_count]           AS [実行された回数], 
        ///    [total_worker_time] / 1000  AS [CPU 時間の合計(msec)],
        ///    [total_worker_time] / [execution_count] / 1000 
        ///                                AS [CPU 時間の平均(msec)], 
        ///    [last_worker_time] / 1000   AS [前回実行時のCPU時間(msec)],
        ///    [max_worker_time] / 1000    AS [最大CPU時間(msec)],
        ///    [min_worker_time] / 1000    AS [最小CPU時間(msec)],
        ///    --[name] AS [オブジェクト名],
        ///     [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rcQueryPlan {
            get {
                return ResourceManager.GetString("rcQueryPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   select schema_id, name from sys.schemas に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rcSchemaInfo {
            get {
                return ResourceManager.GetString("rcSchemaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   select uid, name from sys.sysobjects where type = &apos;U&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rcTableInfo {
            get {
                return ResourceManager.GetString("rcTableInfo", resourceCulture);
            }
        }
    }
}
